### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#1]
ให้แต่ละคนคอมเม้น idea ลงใน github ได้เลยนะครับแล้วให้อธิบายideaตามหัวข้อนี่
1.เกมเล่นยังไง(หมายถึงว่าลักษณะ gameplay เป็นยังไง เช่น ยิงยานอวกาศเพื่อเก็บแต้ม เพื่อนำไป upgrade จนครบด่านที่กำหนด)
2.คอนโทรลยังไง(ใช่คีบอร์ดเดินและใช้เม้าแบบเกมทั่วไป หรือเกมเป็นแนวเนื้อเรื่องคลิกเพื่อเลือกคำตอบเท่านั้น)
3.theme เกมเป็นยังไง(ธีมในเชิงศิลปะ เช่น ธีมอวกาศ )
4.ความคิดเห็นเพิ่มเติม \\ไม่จำเป็น

**Comment by Naihtton** [comment]
เก่งมากครับ

**Comment by SkyEngineerME** [comment]
สวัสดีครับทุกคนสอบเป็นไงกันบ้างครับ วันที่4กันยา(วันอาทิตย์)เรามีกำหนดการต้องนำเสนอไอเดียเกมกันแล้วนะครับ

**Comment by SkyEngineerME** [comment]
ไอเดียของผมนะครับ ผมคุยกับdesignerไว้นะครับซึ่งไอเดียส่วนใหญ่มาจากดีไซเนอร์นะ
1.เกมคือเราจะให้ผู้เล่นเนี่ยต่อสู้ไปกับศัตรูในแต่ละด้านแล้วเก็บแต้มเพื่อ Upgrade ตัวละครไปเรื่อยๆสามารดเล่นซำ้แต่ละด่านได้ แล้วแต่ละด้านจะมีบอสให้ผู้เล่นตี
2.การคอนโทรลก็ใช้ wasd ในการเดินปกติครับใช้เมาในการตี และบล็อค
3.ธีมเกมคือ วิศวมช แต่ละด้านก็จะมีฉาก ห้องdrawingหรือแล็ปและมีอาจารย์ roger เป็น final boss

**Comment by HoloLirny** [comment]
เห็นด้วยกับความคิดเห็นด้านบนนะ มีตะหงิดๆอยู่บ้าง เพราะอาจจะยังมองเห็นภาพไม่ชัด แต่คิดเอาไว้ตอนนี้ก็ยากอยู่พอสมควร อาจจะต้องปรับกันนิดนึง เอาเป็นว่าเห็นด้วย

**Comment by Naihtton** [comment]
เห็นด้วยใน ข้อ 1 และ 2 ครับเรื่องธีมเกมยังมองภาพไม่ค่อยออก แต่ระบบการเล่นหลักๆตามข้อ 1,2 น่าสนใจแล้วครับ

**Comment by TheeraphanPhanwattanasin** [comment]
ขอขยายความธีมเพิ่มเติมจาก manager นะครับ
- พูดง่าย ๆ คือ การเข้าไปตีบอสในดันเจี้ยน ซึ่งก็คือ การที่เราเข้าไปตีกับอาจารย์แต่ละวิชานั่นแหละครับ
- โดยสมมติจะมี 5 ด่าน แต่ละด่านก็จะมีธีมเป็นวิชาแต่ละวิชา เช่น ด่าน 1 เราก็จะเข้าไปตีกับอาจารย์วิชาแคล ด่านถัด ๆ มา ก็จะไปสู้กับอาจารย์ฟิสิกส์ อาจารย์ดรอว์อิ้ง ฯลฯ
- สถานที่ที่เป็นดันเจี้ยนในเกมนี้คือ ตึก 30 ปีที่เราเรียนครับ ถ้าเราตีอาจารย์ชนะผ่านด่านนึงไปได้แล้ว เราก็จะขึ้นลิฟต์ไปด่านถัดไปครับ
- ตอนตีบอสจบ ก็จะมี item ไว้อัปเกรดสกิลตัวเรา หรืออาวุธให้แข็งแกร่งขึ้น

ประมาณนั้นครับ

**Comment by HoloLirny** [comment]
จริงๆก็มีเรื่องอยากถามเยอะอยู่นะ แต่เดียวรอไปคุยพรุ่งนี้เลยแล้วกัน

**Comment by SkyEngineerME** [comment]
เกมเราเดิน ซ้าย-ขวานะครับ แบบ2D
