### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#12]

**Comment by TheeraphanPhanwattanasin** [comment]
https://drive.google.com/drive/folders/1TR43Dsu8zvoWhJdDC6xYONcGYo9Hg8pn?usp=sharing

**Comment by SkyEngineerME** [comment]
ขอเสียง monโดนตีด้วยครับกับเปลี่ยนเสียงไม้ทีมันดูไม่ค่อยเข้ากัน
