### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#13]

**Comment by TheeraphanPhanwattanasin** [comment]
Intro Story
: https://scratch.mit.edu/projects/731789104

Dialogue Stage 1: https://scratch.mit.edu/projects/731869015
Dialogue Stage 2: https://scratch.mit.edu/projects/731898344
Dialogue Stage 3: https://scratch.mit.edu/projects/731904159

Dialogue หลัง Roger ตาย: https://scratch.mit.edu/projects/731923967
