### ISSUE TITLE
อ้างอิง moveset monster

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#14]

**Comment by TheeraphanPhanwattanasin** [comment]
นี่เป็น idea ที่เคยคิดไว้สำหรับ boss แต่ละตัวครับ ถ้ามันมีข้อจำกัดอะไรก็สามารถปรับแต่ง movement ได้ตามสบายเลยครับ ไม่ว่ากัน

[Movement Idea.pdf](https://github.com/SkyEngineerME/-scratch/files/9535266/Movement.Idea.pdf)

**Comment by TheeraphanPhanwattanasin** [comment]
![AE5A4EBF-5A5A-4104-BE77-0FBF440C68B0](https://user-images.githubusercontent.com/110962879/189347168-5e412122-5fd9-4cd5-8df1-7885eab2da03.jpg)
![709128A6-EC82-40FE-8A57-CC24279D512C](https://user-images.githubusercontent.com/110962879/189347163-b549b251-7659-457b-b399-5b9218191b49.jpg)
![749F79F5-B101-4D03-8235-C4F85B5853FC](https://user-images.githubusercontent.com/110962879/189347155-436b38b0-b395-4a2b-beb2-4ee71bde8048.jpg)
![1B8693D7-3708-4EEA-9B20-2478713D629A](https://user-images.githubusercontent.com/110962879/189347142-a3af7d4f-7b7b-47cc-ba5a-037a35a4af72.jpg)

**Comment by Naihtton** [comment]
monster 2 issued 

- [ ] bullet shooting method (how to shoot all the bullets from all mons2 in the same time)
