### ISSUE TITLE
Boss

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#15]

**Comment by Naihtton** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/95070951/189835342-f52d2773-75cd-463d-b850-ba576f250a0d.png">

**Comment by Naihtton** [comment]
<img width="510" alt="Screen Shot 2565-09-13 at 14 15 25" src="https://user-images.githubusercontent.com/95070951/189838534-9398ccb6-5529-46d9-a237-8065ff54cbe2.png">

**Comment by Naihtton** [comment]
overdamaged when touched the boss is fixed
T damaged overtime is fixed

**Comment by HoloLirny** [comment]
https://scratch.mit.edu/projects/732228542
last Boss

**Comment by Naihtton** [comment]
![image](https://user-images.githubusercontent.com/95070951/190845925-d239abc5-496a-4581-a6b4-067169a19562.png)
BOSS 2 moveset completed

**Comment by Naihtton** [comment]
![image](https://user-images.githubusercontent.com/95070951/190846226-5c76f1d9-1777-49d9-be3f-05eb7a55d8ed.png)
issue
- bad optimized on stage obstracle
- monster2 still unfinished

**Comment by Naihtton** [comment]
https://scratch.mit.edu/projects/731801631/editor
latest boss 2 and stage 2 moveset (still have a lot to do)

**Comment by Naihtton** [comment]
![image](https://user-images.githubusercontent.com/95070951/190953703-c5c085dd-8e39-444e-b7fd-af6255a3fbe8.png)
pencil hover over backdrop fixed

**Comment by HoloLirny** [comment]
https://scratch.mit.edu/projects/733261964
last boss finish

**Comment by Naihtton** [comment]
boss2 finished
https://scratch.mit.edu/projects/733801133/
