### ISSUE TITLE
bug จากการใส่story boss1

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#17]

**Comment by SkyEngineerME** [comment]
มีบักจาก story คือ เมื่อมีบทสนทนา 6 บทจะทำให้ monster spawn เป็น wave 
https://scratch.mit.edu/projects/731751891/editor

**Comment by SkyEngineerME** [comment]
แต่แก้ไขได้เพียงแค่เปลี่ยนค่าจำนวนบทสนทนา จาก 6 เป็น 5

**Comment by SkyEngineerME** [comment]
@TheeraphanPhanwattanasin  จะโอเคมั้ยถ้าประโยคหายไปบทหนึ่ง

**Comment by TheeraphanPhanwattanasin** [comment]
ไม่เจอ bug แล้ว
