### ISSUE TITLE
(Boss2) Mon2 Shooting problem 

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#18]

**Comment by SkyEngineerME** [comment]
พี่เติ้ล @Naihtton ถ้าเกิดแก้ไม่ได้จริงๆ ให้ดินสอยิงออกมาใส่ตัวละครหลักเลยก็ได้

**Comment by Naihtton** [comment]
ไม่ๆปัญหาไม่ได้อยู่ที่ boss2 แล้วตอนนี้ อยู่ที่ mons2 ถ้าเสร็จแล้วก็ประกอบจบได้เลย
ปัญหาคือให้มัน spawn อยู่กับที่หลายๆตัวแล้วให้มันยิง4ทิศ ตอนนี้กำลังหาวิธีให้ยิงแบบใส่ตัวละครหลักแทนอยู่

**Comment by Naihtton** [comment]
moveset changed and finished
