### ISSUE TITLE
Monster

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#3]
เขียนโปรแกรมศัตรู

**Comment by Naihtton** [comment]
Sorting and searching for ENEMY moving algorithm.

**Comment by Naihtton** [comment]
https://scratch.mit.edu/projects/730526987

wave system completed

**Comment by Naihtton** [comment]
<img width="506" alt="Screen Shot 2565-09-11 at 17 15 55" src="https://user-images.githubusercontent.com/95070951/189522346-cff2d7c1-280f-4b06-8a61-5874a1f484a8.png">

optimized monster spawner

**Comment by Naihtton** [comment]
![image](https://user-images.githubusercontent.com/95070951/191012048-dfb495fd-eda8-4c0b-b4a3-2d6bf1e1fe4a.png)
monster 2 finished + comment
