### ISSUE TITLE
ระบบเกม(การupgrade)

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#4]
เขียนโปรแกรมระบบการอัพเกรด

**Comment by SkyEngineerME** [comment]
หนุนอัพเกรด ขออัพเกรดหลังจากสู้มอน 3waveก่อนสู้บอส แล้วการอัพเกรดมีสองสายคือไม้ทีกับเฟือง ของอัพเกรดเชื่อมทั้ง 3 ด่าน(อัพเกรด ไม้ที Lv2 เฟืองไม่อัพเกรด Lv1 ด่านต่อไป อัพไม้ทีเป็น Lv3 ไม่อัพเฟือง Lv1) โอเคมั้ย

**Comment by HoloLirny** [comment]
เดียวนะ wave monster กูต้องเขียนไหม หรือให้คนที่ทำmonsterเขียน
