### ISSUE TITLE
Concept art

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#5]
Concept art ทั้งหมด

**Comment by TheeraphanPhanwattanasin** [comment]
![Gameplay](https://user-images.githubusercontent.com/110962879/188463173-a9f43271-671e-43af-82b6-9b0cf77e997b.jpg)

![Player_Design](https://user-images.githubusercontent.com/110962879/188463167-dbbc2f21-852c-4f0b-b537-a96169725309.jpg)

![Boss_Design](https://user-images.githubusercontent.com/110962879/188463176-7aef3302-4473-446c-b2e9-8c9783cede91.jpg)

![Stage](https://user-images.githubusercontent.com/110962879/188463165-0647a9b3-5768-4064-bc29-6603fa0278ff.jpg)

![Weapon](https://user-images.githubusercontent.com/110962879/188463155-0cc541bf-c740-401d-afde-249c4b899f63.jpg)

![Money](https://user-images.githubusercontent.com/110962879/188463169-949cb4e9-35e5-477f-bd0f-37bc56cdfe65.jpg)

**Comment by TheeraphanPhanwattanasin** [comment]
![26D85D99-4C9C-4218-8A27-A362DC6174D5](https://user-images.githubusercontent.com/110962879/188544853-dda64330-91c4-4b71-b012-38bd4433eb6e.jpg)

**Comment by TheeraphanPhanwattanasin** [comment]
[[](url)](https://drive.google.com/drive/folders/1zQfhmVcbgpzREIWeutbJpo4J7e9wM3od?usp=sharing)

**Comment by TheeraphanPhanwattanasin** [comment]
[https://drive.google.com/drive/folders/1zQfhmVcbgpzREIWeutbJpo4J7e9wM3od?usp=sharing](url)

**Comment by TheeraphanPhanwattanasin** [comment]
ไฟล์ Scratch กดซะะะ

  https://drive.google.com/drive/folders/1zQfhmVcbgpzREIWeutbJpo4J7e9wM3od?usp=sharing   <<<

**Comment by TheeraphanPhanwattanasin** [comment]
ตอนนี้ พวก sprite ที่จำเป็นต่อตัวระบบตอนนี้ผมน่าจะทำหมดเรียบร้อยแล้วนะครับ หากต้องการ sprite หรือต้องการแก้ไขอะไรเพิ่มเติมสามารถบอกกันมาได้ จะได้ช่วยแก้ไขครับ

**Comment by Naihtton** [comment]
ขอกระสุนบอส 1 หน่อยจ้า

**Comment by TheeraphanPhanwattanasin** [comment]
animation Roger edit:
https://drive.google.com/drive/folders/1-1C6oJJTGRHlBUQSPcZUCXJZGuWx6auE?usp=sharing
