### ISSUE TITLE
เกมสมบูรณ์

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#8]

**Comment by SkyEngineerME** [comment]
Entaneer Dungeon V1.0: https://scratch.mit.edu/projects/734216439/

**Comment by SkyEngineerME** [comment]
Entaneer Dungeon V1.1:https://scratch.mit.edu/projects/734216439/editor/
-แก้เสียงเพลง Boss1
-แก้บทสนทนา อยู่หลังตัวละคร

**Comment by HoloLirny** [comment]
Entaneer Dungeon V1.2https://scratch.mit.edu/projects/734304968
แก้นิดหน่อย

**Comment by SkyEngineerME** [comment]
Entaneer Dungeon V1.3:https://scratch.mit.edu/projects/734349420/editor
-เพิ่มฉากจบ

**Comment by TheeraphanPhanwattanasin** [comment]
Entaneer Dungeon V1.4:https://scratch.mit.edu/projects/734766378/editor/
-แก้ดินสอกับเลือดไม่หายหลังจากจบเกท

**Comment by Naihtton** [comment]
Entaneer Dungeon V1.5 : https://scratch.mit.edu/projects/734782448/
GAME OVER

**Comment by TheeraphanPhanwattanasin** [comment]
Final: https://scratch.mit.edu/projects/734790299
Ver.แก้หน้างาน No bug P E R F E C T

**Comment by SkyEngineerME** [comment]
Entaneer Dungeon V1.6(final กว่า):https://scratch.mit.edu/projects/736910776/editor
