### ISSUE TITLE
ริวิวเกมหลังจบ

### ISSUE THREAD

**Issue by SkyEngineerME** [SkyEngineerME/-scratch#9]

**Comment by HoloLirny** [comment]
V 1.0 -ยังมีบัคเรื่องเสียงเวลาเปลี่ยนด่าน1ไป2
         -bossด่าน1ทับบทสนทนา
         -อาจจะมาจากบัค1เพราะว่าไม่มีเสียงประกอบด่าน2
         -ปรับเวลาชนบอสเลือดไม่ลด แต่ดันเพิ่มแทน
         -อันอาจจะแค่test เพราะ damage gear แรงไป
         -มอน2ยิงช้าไป กว่าจะเกิด เดินมา แล้วยิง ก็โดนเราเก็บเรียบแล้ว(ตอนเปิดตัวนะ)
         -เวลาเหลือไหม เราควรมีหน้าจบเกมดีๆ
         -ตอนที่ตายทุกครั้งน่าจะบอกคนอื่นให้กดธงเขียวทุกครั้ง เพราะมีสิทธิ์ที่จะมีบ้างอย่างจะค้างอยู่
